### ISSUE TITLE
丰富文档、调整Component命名与替换测试框架的建议

### ISSUE THREAD

**Issue by liupeng110112** [zle-loves-e2e/zle#3]
@focalism @indexmotion 看了下todomvc案例 简单提下自己的看法：
-  缺少该类库特性描述文档
-  zle导出的Component，容易和react开发中的Componet混淆，这里的应该是指某个区块的描述，而不是真正的组件吧 ，是否替换成偏描述性的词语 比如 区块、模块等之类
- mocha是否可以替换成jest

**Comment by indexmotion** [comment]
> 缺少该类库特性描述文档

请问特性描述文档是指更具体的指导说明？比如React官方文档的Quick Start和Advanced Guides系列章节？

> zle导出的Component，容易和react开发中的Componet混淆，这里的应该是指某个区块的描述，而不是真正的组件吧 ，是否替换成偏描述性的词语 比如 区块、模块等之类

这个可以，我也认为这里叫Component会对用户理解、以及沟通过程造成一定困扰。如果仅站在UI定义的视角，Component就是对形状（Shape）描述，但Component及其子类还提供了操作这块区域的方法，所以叫Panel（面板）也很准确（关于面板取名，也是在 http://www.infoq.com/cn/articles/martin-fowler-basic-rule-of-thumbon-for-Web-testing 这篇文章中讨论到的）。 @focalism 有什么取名建议？

> mocha是否可以替换成jest

对jest不太熟悉，和mocha相比它有哪些不错的特性？

**Comment by liupeng110112** [comment]
@indexmotion  

> 缺少该类库特性描述文档
比如解决了什么问题，支持哪些功能，另外把类库的api文档开放出来，不然要看你的todomvc才知道有哪些api了

> 对jest不太熟悉，和mocha相比它有哪些不错的特性？
基本不用配置而且内置了大量库  具体查看下https://facebook.github.io/jest/zh-Hans/

**Comment by indexmotion** [comment]
经讨论，决定使用 `Panel` 替代 `Component` 的名称，另两个建议已开辟[#6](https://github.com/zle-loves-e2e/zle/issues/6)和[#7](https://github.com/zle-loves-e2e/zle/issues/7)单项处理，后面重命名的commit会关闭本问题。
