### ISSUE TITLE
在组件里面通过名称获取`ElementHandle`列表

### ISSUE THREAD

**Issue by focalism** [zle-loves-e2e/zle#8]
```
export class A extends Panel {
  static $definition = UIDefinition.root(
    "div.test","menu")
    .withDescendant("li.item", "item");
```
面板A是一个列表，列表里面包含多个"item",现在想要获取A里面的所有的"item".

可以单独的将item定义为一个面板,然后通过`$selectAll`的方法,获取所有的`item`,但是这样显得很繁琐.

希望能直接在面板A里面获取所有的`item`,而不是定义新的面板.

**Comment by indexmotion** [comment]
首先不建议将列表里的li元素嵌入到UIDefinition，这在我看来不是最佳实践，理由是应考虑到列表为空的情形，那样就匹配不上了。

解决这个问题，可以直接通过this.$elementHandle.$$("li.item")。
